-- 코드를 입력하세요
SELECT E.REST_ID, E.REST_NAME ,
E.FOOD_TYPE, E.FAVORITES, E.ADDRESS, ROUND(AVG(J.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO E INNER JOIN REST_REVIEW J
ON E.REST_ID = J.REST_ID
WHERE SUBSTR(ADDRESS, 1 , 2) = '서울'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;